{
  imports = [
    ./_1password.nix
    ./claude-code.nix
    ./dank-material-shell.nix
    ./dev-tools.nix
    ./direnv.nix
    ./firefox.nix
    ./ghostty.nix
    ./git.nix
    ./neovim.nix
    ./nimbalyst.nix
    ./niri.nix
    ./obs.nix
    ./shell.nix
    ./starship.nix
    ./tmux.nix
    ./user-packages.nix
  ];
}
