{
  imports = [
    ./_1password.nix
    ./audio.nix
    ./aws.nix
    ./claude-code.nix
    ./creative.nix
    ./dank-material-shell.nix
    ./dev-tools.nix
    ./direnv.nix
    ./dropbox.nix
    ./firefox.nix
    ./ghostty.nix
    ./git.nix
    ./gtk-theme.nix
    ./kubernetes.nix
    ./mpv.nix
    ./mullvad.nix
    ./neovim.nix
    ./networkmanager.nix
    ./niri.nix
    ./postgres-cli.nix
    ./shell.nix
    ./spotify.nix
    ./starship.nix
    ./tmux.nix
    ./user-packages.nix
    ./wayland-tools.nix
    ./wireguard.nix
  ];
}
