{
  imports = [
    ./_1password.nix
    ./amd-gpu.nix
    ./audio.nix
    ./bluetooth.nix
    ./creative.nix
    ./dank-material-shell.nix
    ./dropbox.nix
    ./fonts.nix
    ./mullvad.nix
    ./networkmanager.nix
    ./niri.nix
    ./podman.nix
    ./printing.nix
    ./server.nix
    ./steam.nix
    ./system-packages.nix
    ./wireguard.nix
  ];
}
