{
  imports = [
    ./_1password.nix
    ./amd-gpu.nix
    ./audio.nix
    ./bluetooth.nix
    ./creative.nix
    ./dank-material-shell.nix
    ./dropbox.nix
    ./firefox.nix
    ./fonts.nix
    ./ghostty.nix
    ./gtk-theme.nix
    ./ktorrent.nix
    ./mpv.nix
    ./mullvad.nix
    ./nautilus.nix
    ./networkmanager.nix
    ./niri.nix
    ./podman.nix
    ./printing.nix
    ./server.nix
    ./spotify.nix
    ./steam.nix
    ./vesktop.nix
    ./wayland-tools.nix
    ./wireguard.nix
  ];
}
